name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: grepnull
        password: ${{ secrets.DOCKER_KEY }}
        repository: gloomhaven-helper
        tag_with_ref: true
        tag_with_sha: true
        add_git_labels: true

